<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * Part of the Paymentmodul of Novalnet AG
 * http://www.novalnet.de 
 * If you have found this script usefull a small        
 * recommendation as well as a comment on merchant form 
 * would be greatly appreciated.
 * 
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2008 Novalnet AG
 * @version    1.0.0
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
	$code=$this->getMethodCode();
?>
<fieldset class="form-list">
	<ul id="payment_form_<?php echo $code ?>" style="display:none">
		<li>
			<?php echo $this->__('You will be redirected to our secure payment page when you place an order.') ?>
            <img style="float:right;" width="170" src="<?php echo Mage::helper("Merchantware_Merchantware")->getImageUrl()?>mw_logo.png" />
		</li>
	</ul>
</fieldset>
